name: "Runs peckish"
description: "Runs peckish at pwd"
runs:
  using: "node16"
  main: "../dist/peckish_run.js"
inputs:
  config:
    description: "peckish config file"
    required: false
    default: "peckish.yaml"
